name: antlr4_builder_example
description: An example project for antlr4_builder.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  antlr4_builder:
    path: ../ # Path to the antlr4_builder package
  antlr4: ^4.12.0 # Version of antlr4 used by the generated code

dev_dependencies:
  build_runner: ^2.0.0