name: antlr4_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
topics:
  - build-runner
  - codegen
  - antlr
environment:
  sdk: ^3.3.4

dependencies:
  build: ^3.0.2
  http: ^1.0.0
  path: ^1.8.0
  scratch_space: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  build_verify: ^3.1.1
  build_runner: ^2.0.0
  build_test: ^3.3.2
